### ISSUE TITLE
Feature tests for Business Bookings module

### ISSUE THREAD

**Issue by b8ne** [SENG3160-2018/flightpub#12]
**Is your feature request related to a problem? Please describe.**
Currently there are no unit or feature tests for this code.

**Describe the solution you'd like**
Implement feature tests using JUnit with maximum coverage.

**Comment by b8ne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Module C - Business Bookings](https://trello.com/c/YjBMq2VI/25-module-c-business-bookings)

**Comment by ebbanat** [comment]
![email](https://user-images.githubusercontent.com/16621776/47693622-7dbe8d80-dc4e-11e8-8cf9-42faac145785.png)
![confirm](https://user-images.githubusercontent.com/16621776/47693623-7dbe8d80-dc4e-11e8-8a1e-70dc72243c71.png)
