### ISSUE TITLE
Incorrect prompts in Checkout

### ISSUE THREAD

**Issue by b8ne** [SENG3160-2018/flightpub#5]
**Describe the bug**
When viewing checkout incorrect prompts are displayed.

**To Reproduce**
1. Select 'Business' user type.
2. Go through and add a flight to cart.
3. From checkout go to homepage, select 'Group Booking'
4. Complete query form to go to results listing.
5. Select 'Proceed to Checkout' under 'Cart Preview.'
6. Alert message and above cart list show 'Not booking for everyone, but still want your friends to know about this flight? Click the Share with a friend button!' 

**Expected behavior**
This message should not appear if no group bookings are selected.

**Screenshots**
![screen shot 2018-10-12 at 1 20 31 pm](https://user-images.githubusercontent.com/19263633/46844188-a9094600-ce21-11e8-9ad2-08f260bee1c3.png)

**Comment by joelpaxton** [comment]
Branch Issue 3 should fix this issue, see SearchAction.java
