### ISSUE TITLE
Email confirmation/receipt appears to hang

### ISSUE THREAD

**Issue by b8ne** [SENG3160-2018/flightpub#7]
**Describe the bug**
After purchase, when sending confirmation email, the page appears to hang while the email is sent.
Assuming this is due to server side jobs that process synchronously.

**To Reproduce**
1. Purchase any flight.
2. On confirmation screen enter name and email.
3. Submit form.

**Expected behavior**
A loading dialog/spinner should appear either as a screen overlay or in the submit button to show the user that something is happening and prevent them from closing the window or clicking away.

**Comment by ebbanat** [comment]
It takes java a lot longer than the usual speed to process and send the email relative to the normal speed of using the website it appears slower than usual.

Solution: Give user feedback while the email is being sent.

![sendingemail](https://user-images.githubusercontent.com/16621776/47623131-7077a500-db61-11e8-85b7-adf20a91ebd9.png)
